CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(255),
    email VARCHAR(255) NOT NULL UNIQUE,
    mobile_number VARCHAR(255),
    password VARCHAR(255),
    profile_image TEXT,
    address TEXT,
    role VARCHAR(50),
    created_at TIMESTAMP
);

CREATE TABLE restaurants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    cuisine VARCHAR(255),
    image TEXT,
    delivery_time VARCHAR(255),
    rating DOUBLE PRECISION NOT NULL,
    offer VARCHAR(255),
    description TEXT
);

CREATE TABLE foods (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id BIGINT,
    name VARCHAR(255),
    category VARCHAR(255),
    description TEXT,
    image TEXT,
    veg BOOLEAN NOT NULL,
    rating DOUBLE PRECISION NOT NULL,
    price DOUBLE PRECISION NOT NULL
);

CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    restaurant_id BIGINT,
    restaurant_name VARCHAR(255),
    subtotal DOUBLE PRECISION NOT NULL,
    gst DOUBLE PRECISION NOT NULL,
    delivery_charge DOUBLE PRECISION NOT NULL,
    grand_total DOUBLE PRECISION NOT NULL,
    delivery_address TEXT,
    mobile_number VARCHAR(255),
    payment_method VARCHAR(50),
    status VARCHAR(50),
    order_date TIMESTAMP
);

CREATE TABLE order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT,
    food_id BIGINT,
    name VARCHAR(255),
    price DOUBLE PRECISION NOT NULL,
    quantity INTEGER NOT NULL,
    image TEXT,
    CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE
);

CREATE INDEX idx_foods_restaurant_id ON foods(restaurant_id);
CREATE INDEX idx_orders_user_id_order_date ON orders(user_id, order_date DESC);
CREATE INDEX idx_order_items_order_id ON order_items(order_id);
